name: porfolio
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/www/portfolio:/var/www/portfolio
      - ./nginx/ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - portfolio_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - portfolio_network


  node-weather-app:
    container_name: node-weather-app
    build: ./projects/node-weather-app/.
    ports:
      - "3000:3000"
    networks:
      - portfolio_network

  go-chat-app:
    container_name: go-chat-app
    build: ./projects/go-chat-app/backend/.
    ports:
      - "8080:8080"
    networks:
      - portfolio_network

  python-data-visualizer:
    container_name: python-data-visualizer
    build: ./projects/python-data-visualizer/.
    env_file:
      - ./projects/python-data-visualizer/.env
    ports:
      - "8000:8000"
    networks:
      - portfolio_network

  grid-traversal:
    container_name: grid-traversal
    build: ./projects/grid-traversal/.
    volumes:
      - ./projects/grid-traversal/dist:/dist
    command: ["echo", "Grid Traversal build complete"]

  # app:
  #   image: your_app_image
  #   container_name: app_container
  #   networks:
  #     - portfolio_network

networks:
  portfolio_network:
    external: true
