services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  combined:
    build:
      context: .
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
