services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV:-production}
